baseURL: "https://experiments.romeosarkar10x.com/"
languageCode: en-us
title: "Romeo Sarkar's Experiments"

theme: "basic"

author:
    name: Romeo Sarkar
    email: mail@romeosarkar10x.com
    username: romeosarkar10x
    location: India
    phone: +91-9635332700
    github: github.com/romeosarkar10x

markup:
    goldmark:
        renderer:
            unsafe: true
    # [markup.goldmark]
    # [markup.goldmark.renderer]
        # unsafe = true  # Allows HTML in Markdown
    # [markup.highlight]
    # noClasses = false

    highlight:
        codeFences: true
        guessSyntax: false
        lineNoStart: 1
        lineNos: true
        style: "catppuccin-latte"
        tabWidth: 4