version: "1.0"
githubURL: "https://github.com/romeosarkar10x/experiments"

owner:
    name: Romeo Sarkar
    username: romeosarkar10x
    url: https://romeosarkar10x.com
    location: India
    contact:
        phone: "9635332700"
        email: mail@romeosarkar10x.com
        github: https://github.com/romeosarkar10x
        linkedin: https://linkedin.com/in/romeosarkar10x
        twitter: https://x.com/romeosarkar10x
        youtube: https://youtube.com/@romeosarkar10x
        discord: https://discordapp.com/users/romeosarkar10x
        whatsapp: https://wa.me/qr/ZT3VY2MULEWTH1
        telegram: https://t.me/romeosarkar10x
