name: "deploy"
description: "Check formatting, build (hugo) and deploy to Cloudflare Pages."

on:
  push:
    branches:
      - main

jobs:
  job-deploy:
    runs-on: [self-hosted, Linux, X64, homelab]
    environment: production

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: ./.github/actions/deploy
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
