name: check, build and deploy to cloudflare pages

on:
  push:
    branches:
      - main

env:
  DART_SASS_VERSION: 1.86.3

jobs:
  check-build-and-deploy:
    runs-on: [self-hosted, Linux, X64]
    environment: production

    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: "23"

      - name: install dependencies
        run: npm install

      - name: check
        run: npm run check-format

      - name: install hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: "latest"

      - name: install dart-sass
        uses: dw-labs-org/dart-sass-gha@v1

      - name: build hugo site
        run: |
          echo building hugo site at $(date)
          hugo

      - name: install wrangler
        run: npm install -g wrangler

      - name: deploy to cloudflare pages
        run: wrangler pages deploy ./public --project-name=expt --branch=main --commit-dirty=true --production
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
